config/routes.rb
RailsDevisePundit::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

	#get '/schools' => 'schools#index', as: :schools
	#get '/schools/new' => 'schools#new', as: :new_school
	#post 'schools' => 'schools#create'
	#get 'schools/:id' => 'schools#show', as: :school
	#get 'schools/:id/edit' => 'schools#edit', as: :edit_school
	#patch '/schools/:id' => 'schools#update'
	#delete '/schools/:id' => 'schools#destroy'

	get 'schools/:id/generate' => 'schools#generate', as: :generate_pupils
	get 'schools/:id/distribute' => 'pupils#distribute', as: :distribute_pupils

	#get 'schools/:id/pupils' => 'pupils#index', as: :pupils
	#get 'schools/:id/pupils/new' => 'pupils#new', as: :new_pupils
	#post 'schools/:id/pupils' => 'pupils#create'
	#get 'schools/:id/pupils/:id' => 'pupils#show', as: :pupil
	#get 'schools/:id/pupils/:id/edit' => 'pupils#edit', as: :edit_pupil
	#patch '/schools/:id/pupils/:id' => 'pupils#update'
	#delete '/pupils/:id' => 'pupils#destroy'

	resources :schools do
		resources :pupils
	end

	resources :schools do
		resources :classrooms
	end

end

app/views/shared/view.html.erb
<!-- -->
<div class="school">
  <div class="container">   
  		<p>Name of the school: <%= @school.title %></p>
			<p>School ID: <%= @school.id %></p>
        <p>Number of classrooms: <%= @school.number_of_classrooms %></p>
							<% @school.number_of_pupils = @total_count %>
				<p>Number of pupils: <%= @school.number_of_pupils %></p></br>
        <%= link_to "Edit School", edit_school_path(@school) %>    
  </div>
</div>		

		<% if !@total_count.between?(90,110) %>
				<%= link_to generate_pupils_path(@school), :class=> "button button3" do %>
  					GENERATE PUPILS
				<% end %>
		<% elsif %>
				<h1><%= "There are enough students for this school. (Between 90 and 110)" %></h1>
				<p>You should DISTRIBUTE them among classrooms!</p>
				<%= link_to distribute_pupils_path(@school), :class=> "button button4" do %>
  					DISTRIBUTE PUPILS				
				<% end %>
		<% end %>


		</br>
<%= link_to "Delete School", school_path(@school), method: :delete, data: {confirm: "You sure?"} %></br>
</br>
</br>
<br>	------------------------------------------------------------ 
	<h2>Students for this school: </h2>
	------------------------------------------------------------ 
			
	<% @pupils.each do |pupil| %> 
		<div class="pupil"> 
			<p class="id">Pupil ID: <%= pupil.id %></p> 
			<p class="name">Name of the pupil: <%= pupil.name %></p> 
			<p class="gender">Gender of pupil: <%= pupil.gender %></p> 
			<p class="special">Handicapped?: <%= pupil.special %></p>
			<p class="school">School ID: <%= pupil.school_id %></p>
			<p class="classroom">Classroom ID: <%= pupil.classroom_id %></p> 
					<p class="count">Number of pupils: <%= @total_count %></p> 
		<%= link_to 'Show Pupil', :controller => :pupils, :action => :show, :school_id => pupil.school_id, :id => pupil.id %>
 	</br>
	<br>	------------------------------------------------------------
		</div> 

		<% end %>