config/routes.rb
RailsDevisePundit::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

	#get '/schools' => 'schools#index', as: :schools
	#get '/schools/new' => 'schools#new', as: :new_school
	#post 'schools' => 'schools#create'
	#get 'schools/:id' => 'schools#show', as: :school
	#get 'schools/:id/edit' => 'schools#edit', as: :edit_school
	#patch '/schools/:id' => 'schools#update'
	#delete '/schools/:id' => 'schools#destroy'

	get 'schools/:id/generate' => 'schools#generate', as: :generate_pupils
	get 'schools/:id/distribute' => 'pupils#distribute', as: :distribute_pupils

	#get 'schools/:id/pupils' => 'pupils#index', as: :pupils
	#get 'schools/:id/pupils/new' => 'pupils#new', as: :new_pupils
	#post 'schools/:id/pupils' => 'pupils#create'
	#get 'schools/:id/pupils/:id' => 'pupils#show', as: :pupil
	#get 'schools/:id/pupils/:id/edit' => 'pupils#edit', as: :edit_pupil
	#patch '/schools/:id/pupils/:id' => 'pupils#update'
	#delete '/pupils/:id' => 'pupils#destroy'

	resources :schools do
		resources :pupils
	end

	resources :schools do
		resources :classrooms
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/views/home/index.html.erb
<!--ovo je view za Home tab-->

<h3>Home</h3>
<% if !current_user.nil? and (current_user.admin? or current_user.dean?) %>
  <% @users.each do |user| %>
    <p>User: <%=link_to user.email, user %> Role: <%= user.role unless user.role.nil? %></p>
  <% end %>

		<!--<a href="/schools/new" class="button button1" id="dugme1">Create New School</a>-->
		<%= link_to new_school_path(@school), :class=> "button button1" do %>
  					Create New School				
				<% end %>
		
		<!--	<script type="text/javascript">
				function myFunction() 
				{
						document.getElementById("dugme2").style.visibility = "hidden";
				}
			</script>
		-->
		<!--<a href="/schools" class="button button2" id="dugme2">View Schools</a>-->
		<%= link_to schools_path(@school), :class=> "button button2" do %>
  					View Schools
				<% end %>

<% end %>
			