config/routes.rb
RailsDevisePundit::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

	#get '/schools' => 'schools#index', as: :schools
	#get '/schools/new' => 'schools#new', as: :new_school
	#post 'schools' => 'schools#create'
	#get 'schools/:id' => 'schools#show', as: :school
	#get 'schools/:id/edit' => 'schools#edit', as: :edit_school
	#patch '/schools/:id' => 'schools#update'
	#delete '/schools/:id' => 'schools#destroy'

	get 'schools/:id/generate' => 'schools#generate', as: :generate_pupils
	get 'schools/:id/distribute' => 'pupils#distribute', as: :distribute_pupils

	#get 'schools/:id/pupils' => 'pupils#index', as: :pupils
	#get 'schools/:id/pupils/new' => 'pupils#new', as: :new_pupils
	#post 'schools/:id/pupils' => 'pupils#create'
	#get 'schools/:id/pupils/:id' => 'pupils#show', as: :pupil
	#get 'schools/:id/pupils/:id/edit' => 'pupils#edit', as: :edit_pupil
	#patch '/schools/:id/pupils/:id' => 'pupils#update'
	#delete '/pupils/:id' => 'pupils#destroy'

	resources :schools do
		resources :pupils
	end

	resources :schools do
		resources :classrooms
	end

end

app/models/pupil.rb
class Pupil < ActiveRecord::Base
	enum gender: [:male, :female]
	
	belongs_to :classroom
	belongs_to :school

	def male?
		self.gender == 'male'
	end

	def female?
		self.gender == 'female'
	end

	def self.distribute_pupil_for (school)
		@school = school
		
		@total_count = Pupil.where(school_id: @school.id).count
		@male_pupils = Pupil.where(gender: '0', school_id: @school.id).count 
		@female_pupils = @total_count - @male_pupils

		@pupils_per_classroom = @total_count / @school.number_of_classrooms
		@malePupilsPerClassroom = ((@male_pupils.to_f/@total_count.to_f) * @pupils_per_classroom).to_i
		@femalePupilsPerClassroom = @pupils_per_classroom - @malePupilsPerClassroom

		male_counter=1
		female_counter=1

		Pupil.where(school_id: @school.id, gender: '0').find_each do |ppl|
  			classroom_male=male_counter % @school.number_of_classrooms
  			male_counter += 1
  				if classroom_male==0
  					classroom_male=@school.number_of_classrooms
  				end
			ppl.update(classroom_id: classroom_male)
		end

		Pupil.where(school_id: @school.id, gender: '1').find_each do |ppl|
  			classroom_female = female_counter % @school.number_of_classrooms
  			female_counter += 1
				if classroom_female==0
					classroom_female=@school.number_of_classrooms
				end
			ppl.update(classroom_id: classroom_female)
		end
	end

end

app/controllers/pupils_controller.rb
class PupilsController < ApplicationController
	before_filter :authenticate_user!
	before_filter :verification
	require 'ffaker'
	rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found


	def index
		@school = School.find(params[:school_id])		
		@pupils = Pupil.where(:school_id => @school.id)
		@total_count = Pupil.where(:school_id => @school.id).count

		render template: 'shared/view'				
	end


	def new
		@pupil = Pupil.new		
	end


	def show
		@pupil = Pupil.find(params[:id])
		@school = School.find(params[:school_id])
		@total_count = Pupil.where(:school_id => @school.id).count
	end
	

	def create
		school = School.find(params[:school_id])
		@pupil = school.pupils.new(pupil_params) 
		if @pupil.save 
		  redirect_to action: :show, id: @pupil.id, notice: "New pupil created!"
		else 
			render 'new' 
		end
	end


	def edit
		school = School.find(params[:school_id])
		@pupil = school.pupils.find(params[:id])		
	end


	def update
		school = School.find(params[:school_id])
		@pupil = school.pupils.find(params[:id])
		if @pupil.update(pupil_params)
			redirect_to school_pupil_path, notice: "Pupil updated."
		else
			render 'edit'
		end
	end


	def destroy
		@pupil = Pupil.find(params[:id])
		@pupil.destroy
		redirect_to pupils_path, notice: "Pupil deleted."
	end


	def distribute
		school = School.find(params[:id])
		@school = School.find(params[:id])
		@pupils = Pupil.where(:school_id => school.id)

		Pupil.distribute_pupil_for school
	end


	private
	def pupil_params
		params.require(:pupil).permit(:name, :gender, :special, :school_id, :classroom_id)
	end

	def record_not_found
		render file: 'public/404'
	end

end

app/helpers/pupils_helper.rb
module PupilsHelper
end

app/views/pupils/distribute.html.erb
<!-- -->
<% @pupils.each do |pupil| %> 
		<div class="pupil"> 
			<p class="id">Pupil ID: <%= pupil.id %></p> 
			<p class="name">Name of the pupil: <%= pupil.name %></p> 
			<p class="gender">Gender of pupil: <%= pupil.gender %></p> 
			<p class="special">Handicapped?: <%= pupil.special %></p>
			<p class="school">School ID: <%= pupil.school_id %></p>
			<p class="classroom">Classroom ID: <%= pupil.classroom_id %></p> 
			<p class="count">Total number of classrooms: <%= @school.number_of_classrooms %></p>
			<p class="count">Total number of pupils: <%= @total_count %></p> 
			<p class="count">Number of male pupils: <%= @male_pupils %></p> 
			<p class="count">Number of female pupils: <%= @female_pupils %></p> 
			<p class="count">Pupils per classroom: <%= @pupils_per_classroom %></p> 
			<p class="count">Male pupils per classroom: <%= @malePupilsPerClassroom %></p> 
			<p class="count">Female pupils per classroom: <%= @femalePupilsPerClassroom %></p> 

		<%= link_to 'Show Pupil', :controller => :pupils, :action => :show, :school_id => pupil.school_id, :id => pupil.id %>
 	</br>
	<br>	------------------------------------------------------------
		</div> 

		<% end %>

app/views/pupils/edit.html.erb
<!-- -->
<div class="pupil">
  <div class="container">
   
    <%= form_for [params[:school_id], @pupil], :url => school_pupil_path(params[:school_id], @pupil) do |p| %>		
			
      <%= p.text_area :name %></br>
			<br>
			<%= p.radio_button(:gender, "male") %>
			<%= label(:gender_male, "Male") %>
			<%= p.radio_button(:gender, "female") %>
			<%= label(:gender_female, "Female") %><br>
			<br>
			<br>
			<%= p.check_box(:special) %>
			<%= label(:special, "Is this student handicapped?") %><br>
			<br>
			<%= label(:number_field, "School ID to which the student belongs: ") %>
			<%= p.number_field :school_id %>
			</br>
			<%= label(:number_field, "Classroom ID to which the student belongs: ") %>
			<%= p.number_field :classroom_id %>
			</br>
			<br>
		
      <%= p.submit "Update", :class => "btn" %>
    <% end %> 
    
  </div>
</div> 

app/views/pupils/index.html.erb
	<% @pupils.each do |pupil| %> 
		<div class="pupil"> 
			<p class="id">Pupil ID: <%= pupil.id %></p> 
			<p class="name">Name of the pupil: <%= pupil.name %></p> 
			<p class="gender">Gender of pupil: <%= pupil.gender %></p> 
			<p class="special">Handicapped?: <%= pupil.special %></p>
			<p class="school">School ID: <%= pupil.school_id %></p>
			<p class="classroom">Classroom ID: <%= pupil.classroom_id %></p>
			<p class="count">Number of pupils: <%= $total_count %></p> 
		<%= link_to 'Show Pupil', :action => :show, :id => pupil.id %>
 	</br>
	<br>	------------------------------------------------------------
		</div> 

		<% end %>

app/views/pupils/new.html.erb
<!-- -->

<div class="create">
  <div class="container">

		<%= form_for Pupil.new, :url => {:action => :create, :controller => :pupils} do |p| %>
			<div class="field"> 
				<%= p.label :pupil %><br>
				<br>
				<%= p.text_area :name %> <br>
				<br>
				<%= p.radio_button(:gender, "male") %>
				<%= label(:gender_male, "Male") %>
				<%= p.radio_button(:gender, "female") %>
				<%= label(:gender_female, "Female") %>		<br>
				<br>
				<%= label(:number_field, "School ID to which the student belongs: ") %>
				<%= p.number_field :school_id %>
				<br>
				<%= label(:number_field, "Classroom ID to which the student belongs: ") %>
				<%= p.number_field :classroom_id %>
				<br>
				<%= p.check_box(:special) %>
				<%= label(:special, "Is this student handicapped?") %><br>
				<br>

			</div> 
<br>
			<div class="actions"> 
				<%= p.submit "Create" %> 
			</div> 
		<% end %>	
	</div>
</div>

app/views/pupils/show.html.erb
<!-- -->

<% if @pupil.school_id == @school.id %>

		<div class="pupil">
  		<div class="container">
   
  				<p>Name of the pupil: <%= @pupil.name %></p>
					<p>Pupil ID: <%= @pupil.id %></p>
					<p>Handicapped?: <%= @pupil.special %></p>
					<p>Gender: <%= @pupil.gender %></p>
  		 		<p>School ID: <%= @pupil.school_id %></p>
					<p>Classroom ID: <%= @pupil.classroom_id %></p>
  
	      <%= link_to "Edit", edit_school_pupil_path(params[:school_id], @pupil.id) %>
    
		  </div>
		</div>

		<%= link_to "Delete Pupil", school_pupil_path(params[:school_id], @pupil.id), method: :delete, data: {confirm: "You sure?"} %>


<%end%>